

CREATE TABLE CONSTRAINTS(
id INT PRIMARY KEY NOT NULL,
name VARCHAR(40) NOT NULL ,
title VARCHAR(100) NOT NULL,
date  date NOT NULL
);

INSERT INTO CONSTRAINTS(id,name,title,date)
VALUES( "001", "LabeSky", "LSy", "2023/10/05"),
	  ("002","Labefy","LFy","2024/01/06"),
      ("003", "AstroZoom","AZm","2022/12/20"),
      ("004","Skynet","ArtificialKnowledge","2025/12/20");
      
SELECT * FROM CONSTRAINTS;
DESCRIBE CONSTRAINTS;
ALTER TABLE CONSTRAINTS DROP COLUMN title;
SELECT * FROM CONSTRAINTS;
ALTER TABLE CONSTRAINTS CHANGE date dueDate VARCHAR(20) UNIQUE;
SELECT * FROM CONSTRAINTS;
ALTER TABLE CONSTRAINTS ADD description ENUM("DESCRIBE") ;
SELECT * FROM CONSTRAINTS;
SELECT id,name,dueDate FROM  CONSTRAINTS ORDER BY dueDate ASC ;
SELECT id,name,dueDate FROM  CONSTRAINTS ORDER BY dueDate DESC;
SELECT id,name,dueDate FROM  CONSTRAINTS ORDER BY dueDate ASC LIMIT 2022 ;
SELECT id,name,dueDate FROM  CONSTRAINTS ORDER BY dueDate DESC LIMIT 2025;

