const nome =prompt ("Escolha um nome ")
const idade = prompt("escolha sua idade ")
console.log(typeof  nome ,idade)
// nome saiu como String idade como "22"
// 22 e um numero qualquer String e um nome
console .log (nome ,idade )
// exercicio 02
const roupa=prompt(" voce esta usando camisa ?")
const chinelo2 = prompt(" voce esta usando chinelo ?")
const cor= prompt(" voce esta usando oculos  ?")
let r = false
let chinelo = true 
let cor2 = true
console.log ( roupa , chinelo2 , cor , r , chinelo , cor2 )
//exercicio 03

const numero =prompt ("digite um numero ")
const numero2=prompt("digite outro numero ")
console.log(" o valor A é ",numero2)
console.log (" O valor de B é",numero)